### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by 1f9763** [KleinYuan/tf-object-detection#11]
python app.py

Traceback (most recent call last):
  File "app.py", line 43, in <module>
    demo(mode=STATIC_MODE)
  File "app.py", line 20, in demo
    net.predict(img=img, display_img=img)
  File "/Users/nick/Documents/google_drive/doing/object_detection/tf-object-detection/models/object_detection.py", line 118, in predict
    for i in range(0, num_detections):
TypeError: only integer scalar arrays can be converted to a scalar index

i got this error ,plz help

**Comment by p-ml** [comment]
Replace `for i in range(0, num_detections):` with `for i in range(0, int(num_detections)):`

**Comment by KleinYuan** [comment]
Seems being resolved.
